/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\childrenofthecity.gltf 
*/

import React from 'react'
import * as THREE from 'three'
import { useGLTF, useTexture } from '@react-three/drei'
import { PI, PI2 } from 'three/tsl'

export function Model({ offsetX = 0, offsetY = -4.2, offsetZ = 0, ...props }) {
  const { nodes, materials } = useGLTF(`${process.env.PUBLIC_URL}/models/childrenofthecity.gltf`)
  const texture = useTexture(`${process.env.PUBLIC_URL}/textures/Baked.png`)
  texture.flipY = false
  texture.colorSpace = THREE.SRGBColorSpace

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    lightMapIntensity: 1,
    lightMap: texture,

    side: THREE.DoubleSide
  })

  const textureMaterialSwoosh = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    lightMapIntensity: 3,
    lightMap: texture,
    opacity: 0.7,
    emissiveMap: texture,
    emissiveIntensity: 5,
    roughness: 0.314,
    side: THREE.DoubleSide
  })

const textureMaterialBox = new THREE.MeshStandardMaterial({
    map: texture,
    fog: true,
    side: THREE.DoubleSide
  })

  return (
    <group {...props} dispose={null} position={[offsetX, offsetY, offsetZ]}>
        <mesh geometry={nodes.SurfPatch.geometry} material={textureMaterialSwoosh} position={[0, 1, 0]} rotation={[0, 0.5, 2.7]} scale={[1.2, 1.2, 1.2]}/>
        <mesh geometry={nodes.SurfPatch.geometry} material={textureMaterialSwoosh} position={[3, 1, -5]} rotation={[1.2, 0.3, 0.1]} scale={[0.7, 0.7, 0.7]}/>
        <mesh geometry={nodes.SurfPatch.geometry} material={textureMaterialSwoosh} position={[6, 4.5, -2.5]} rotation={[-0.8, 0.3, 2.9]} scale={[1.5, 1.5, 1.5]}/>
        <mesh geometry={nodes.SurfPatch.geometry} material={textureMaterialSwoosh} position={[1, 7, 4.5]} rotation={[0, -1.5, 2.9]} scale={[0.3, 0.3, 0.3]}/>
        <mesh geometry={nodes.SurfPatch.geometry} material={textureMaterialSwoosh} position={[5, 5, 0]} rotation={[0, 0.3, 0]} scale={[1.2, 1.2, 1.2]}/>
        {/* Instantiate more swoosh meshes as needed */}
        {/* Planes Unused */}
        {/* <mesh geometry={nodes.Plane.geometry} material={textureMaterial} position={[5.566, 0, 0.625]} rotation={[0, 0.532, 0]} />
        <mesh geometry={nodes.Plane001.geometry} material={textureMaterial} position={[-3.883, -0.844, 2.054]} rotation={[0, 0.532, 0]} />
        <mesh geometry={nodes.Plane003.geometry} material={textureMaterial} position={[-2, -2, -10.57]} rotation={[0.1, 0.532, 0.2]} />
        <mesh geometry={nodes.Plane004.geometry} material={textureMaterial} position={[-4.694, 0.967, -11.231]} rotation={[0, 0.532, 0]} />
        <mesh geometry={nodes.Plane002.geometry} material={textureMaterial} position={[1.827, -1.104, -8.57]} rotation={[0, 0.532, 0]} />
        <mesh geometry={nodes.Plane005.geometry} material={textureMaterial} position={[-1.41, -0.683, -10.836]} rotation={[0, 0.532, 0]} />
        <mesh geometry={nodes.Plane006.geometry} material={textureMaterial} position={[1.216, -3.591, -4.715]} rotation={[0, 0.532, 0]} />
        <mesh geometry={nodes.Plane007.geometry} material={textureMaterial} position={[-4.776, 6.09, -9.93]} rotation={[0, 0.532, 0]} /> */}
    </group>
  )
}

useGLTF.preload(`${process.env.PUBLIC_URL}/models/childrenofthecity.gltf`)
